// Mock donations — 24 realistic entries across 8 Indian cities
// Photos: picsum.photos with food-relevant seeds

const now = new Date();
const h   = (hours) => new Date(now.getTime() + hours * 3600000);
const ago = (hours) => new Date(now.getTime() - hours * 3600000);

const MOCK_DONATIONS = [
  // ── DELHI ──────────────────────────────────────────────────────────
  {
    foodName: 'Dal Makhani & Naan',
    category: 'cooked',
    description: 'Freshly made dal makhani, butter naan, and rice. Event leftover from a wedding.',
    ingredients: 'Black lentils, butter, cream, naan, basmati rice',
    allergens: ['dairy', 'gluten'],
    quantity: 80,
    quantityUnit: 'servings',
    preparedAt: ago(2),
    shelfLifeHours: 6,
    expiresAt: h(4),
    pickupWindowStart: now,
    pickupWindowEnd: h(3),
    pickupAddress: { line1: 'Banquet Hall, Karol Bagh', area: 'Karol Bagh', city: 'Delhi', state: 'Delhi', pincode: '110005' },
    contactPhone: '9810123456',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/dalmakhani/600/400',
    sdgTags: ['SDG2', 'SDG12'],
    location: { type: 'Point', coordinates: [77.1925, 28.6519] }
  },
  {
    foodName: 'Chole Bhature (Bulk)',
    category: 'cooked',
    description: 'Restaurant surplus from lunch service — hot chole, fresh bhature. 50 portions.',
    allergens: ['gluten'],
    quantity: 50,
    quantityUnit: 'servings',
    preparedAt: ago(1),
    shelfLifeHours: 5,
    expiresAt: h(4),
    pickupWindowStart: h(0.5),
    pickupWindowEnd: h(2.5),
    pickupAddress: { line1: 'Connaught Place, Block A', area: 'Connaught Place', city: 'Delhi', state: 'Delhi', pincode: '110001' },
    contactPhone: '9811234567',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/cholebhature/600/400',
    sdgTags: ['SDG2', 'SDG3'],
    location: { type: 'Point', coordinates: [77.2167, 28.6315] }
  },
  {
    foodName: 'Mixed Vegetable Biryani',
    category: 'veg',
    description: 'Home-cooked biryani — enough for 30 people. Prepared this morning.',
    allergens: [],
    quantity: 30,
    quantityUnit: 'servings',
    preparedAt: ago(3),
    shelfLifeHours: 8,
    expiresAt: h(5),
    pickupWindowStart: now,
    pickupWindowEnd: h(4),
    pickupAddress: { line1: 'Lajpat Nagar Market', area: 'Lajpat Nagar', city: 'Delhi', state: 'Delhi', pincode: '110024' },
    contactPhone: '9312345678',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/vegbiryani/600/400',
    sdgTags: ['SDG2', 'SDG12', 'SDG17'],
    location: { type: 'Point', coordinates: [77.2432, 28.5665] }
  },

  // ── MUMBAI ─────────────────────────────────────────────────────────
  {
    foodName: 'Pav Bhaji (Large Batch)',
    category: 'veg',
    description: 'Street food vendor surplus — freshly made pav bhaji with extra butter. Ideal for community shelters.',
    allergens: ['dairy', 'gluten'],
    quantity: 100,
    quantityUnit: 'servings',
    preparedAt: ago(1.5),
    shelfLifeHours: 4,
    expiresAt: h(2.5),
    pickupWindowStart: now,
    pickupWindowEnd: h(2),
    pickupAddress: { line1: 'Juhu Chowpatty', area: 'Juhu', city: 'Mumbai', state: 'Maharashtra', pincode: '400049' },
    contactPhone: '9820123456',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/pavbhaji/600/400',
    sdgTags: ['SDG2', 'SDG11'],
    location: { type: 'Point', coordinates: [72.8271, 19.1003] }
  },
  {
    foodName: 'Idli-Sambar Pack (120 pcs)',
    category: 'veg',
    description: 'Catering company surplus from a corporate event. 120 idlis + coconut chutney + sambar.',
    allergens: [],
    quantity: 120,
    quantityUnit: 'pieces',
    preparedAt: ago(2),
    shelfLifeHours: 6,
    expiresAt: h(4),
    pickupWindowStart: now,
    pickupWindowEnd: h(3),
    pickupAddress: { line1: 'BKC Corporate Park', area: 'Bandra Kurla Complex', city: 'Mumbai', state: 'Maharashtra', pincode: '400051' },
    contactPhone: '9821234567',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/idlisambar/600/400',
    sdgTags: ['SDG2', 'SDG3'],
    location: { type: 'Point', coordinates: [72.8656, 19.0607] }
  },
  {
    foodName: 'Chicken Biryani (50 portions)',
    category: 'non_veg',
    description: 'Restaurant surplus from Saturday lunch. Hyderabadi style with raita.',
    allergens: ['dairy'],
    quantity: 50,
    quantityUnit: 'servings',
    preparedAt: ago(2),
    shelfLifeHours: 5,
    expiresAt: h(3),
    pickupWindowStart: h(0.5),
    pickupWindowEnd: h(2.5),
    pickupAddress: { line1: 'Mohammed Ali Road', area: 'Nagpada', city: 'Mumbai', state: 'Maharashtra', pincode: '400008' },
    contactPhone: '9822345678',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/chickenbiryani/600/400',
    sdgTags: ['SDG2'],
    location: { type: 'Point', coordinates: [72.8324, 18.9634] }
  },
  {
    foodName: 'Bread & Jam (Factory Surplus)',
    category: 'bakery',
    description: 'Day-old bread loaves approaching best-by. Perfectly edible. 40 loaves + jam packs.',
    allergens: ['gluten'],
    quantity: 40,
    quantityUnit: 'packets',
    preparedAt: ago(18),
    shelfLifeHours: 30,
    expiresAt: h(12),
    pickupWindowStart: now,
    pickupWindowEnd: h(6),
    pickupAddress: { line1: 'Dharavi Industrial Area', area: 'Dharavi', city: 'Mumbai', state: 'Maharashtra', pincode: '400017' },
    contactPhone: '9823456789',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/breadjam/600/400',
    sdgTags: ['SDG2', 'SDG12'],
    location: { type: 'Point', coordinates: [72.8531, 19.0411] }
  },

  // ── BANGALORE ──────────────────────────────────────────────────────
  {
    foodName: 'South Indian Thali (Weekend)',
    category: 'veg',
    description: 'Hotel surplus — complete thali with sambar, rasam, 3 veg curries, rice, papad.',
    allergens: [],
    quantity: 45,
    quantityUnit: 'servings',
    preparedAt: ago(1),
    shelfLifeHours: 6,
    expiresAt: h(5),
    pickupWindowStart: now,
    pickupWindowEnd: h(3),
    pickupAddress: { line1: 'Koramangala 5th Block', area: 'Koramangala', city: 'Bangalore', state: 'Karnataka', pincode: '560095' },
    contactPhone: '9880123456',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/sithali/600/400',
    sdgTags: ['SDG2', 'SDG3', 'SDG12'],
    location: { type: 'Point', coordinates: [77.6245, 12.9352] }
  },
  {
    foodName: 'Fresh Fruit Basket (Market End-of-Day)',
    category: 'raw_produce',
    description: 'Unsold fruits from organic market — bananas, apples, guavas, papayas. All fresh.',
    allergens: [],
    quantity: 25,
    quantityUnit: 'kg',
    preparedAt: ago(4),
    shelfLifeHours: 48,
    expiresAt: h(44),
    pickupWindowStart: now,
    pickupWindowEnd: h(10),
    pickupAddress: { line1: 'Indiranagar 12th Main', area: 'Indiranagar', city: 'Bangalore', state: 'Karnataka', pincode: '560038' },
    contactPhone: '9881234567',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/fruitbasket/600/400',
    sdgTags: ['SDG2', 'SDG3', 'SDG12'],
    location: { type: 'Point', coordinates: [77.6408, 12.9784] }
  },
  {
    foodName: 'Vegan Salad & Wraps',
    category: 'vegan',
    description: 'Café surplus — 35 wraps and mixed salad bowls from lunch menu. No animal products.',
    allergens: ['gluten'],
    quantity: 35,
    quantityUnit: 'pieces',
    preparedAt: ago(3),
    shelfLifeHours: 5,
    expiresAt: h(2),
    pickupWindowStart: now,
    pickupWindowEnd: h(1.5),
    pickupAddress: { line1: 'HSR Layout Sector 1', area: 'HSR Layout', city: 'Bangalore', state: 'Karnataka', pincode: '560102' },
    contactPhone: '9882345678',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/vegansalad/600/400',
    sdgTags: ['SDG2', 'SDG12'],
    location: { type: 'Point', coordinates: [77.6383, 12.9116] }
  },

  // ── CHENNAI ────────────────────────────────────────────────────────
  {
    foodName: 'Sambar Rice & Appalam (60 packs)',
    category: 'veg',
    description: 'Temple prasad surplus — sambar rice, appalam, and pickle. Pure sattvic food.',
    allergens: [],
    quantity: 60,
    quantityUnit: 'servings',
    preparedAt: ago(2),
    shelfLifeHours: 5,
    expiresAt: h(3),
    pickupWindowStart: now,
    pickupWindowEnd: h(2.5),
    pickupAddress: { line1: 'T Nagar Temple Street', area: 'T Nagar', city: 'Chennai', state: 'Tamil Nadu', pincode: '600017' },
    contactPhone: '9444123456',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/sambarrice/600/400',
    sdgTags: ['SDG2', 'SDG17'],
    location: { type: 'Point', coordinates: [80.2333, 13.0418] }
  },
  {
    foodName: 'Fish Curry & Rice',
    category: 'non_veg',
    description: 'Coastal restaurant surplus from Sunday special. Chettinad fish curry, steamed rice.',
    allergens: ['fish'],
    quantity: 40,
    quantityUnit: 'servings',
    preparedAt: ago(1.5),
    shelfLifeHours: 4,
    expiresAt: h(2.5),
    pickupWindowStart: now,
    pickupWindowEnd: h(2),
    pickupAddress: { line1: 'Besant Nagar 2nd Avenue', area: 'Besant Nagar', city: 'Chennai', state: 'Tamil Nadu', pincode: '600090' },
    contactPhone: '9445234567',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/fishcurry/600/400',
    sdgTags: ['SDG2', 'SDG14'],
    location: { type: 'Point', coordinates: [80.2673, 13.0002] }
  },

  // ── HYDERABAD ──────────────────────────────────────────────────────
  {
    foodName: 'Hyderabadi Haleem (Large Pot)',
    category: 'non_veg',
    description: 'Special Ramadan haleem leftover — authentic Haleem with wheat and mutton. 70 servings.',
    allergens: ['gluten'],
    quantity: 70,
    quantityUnit: 'servings',
    preparedAt: ago(3),
    shelfLifeHours: 8,
    expiresAt: h(5),
    pickupWindowStart: now,
    pickupWindowEnd: h(3),
    pickupAddress: { line1: 'Charminar Old City', area: 'Old City', city: 'Hyderabad', state: 'Telangana', pincode: '500002' },
    contactPhone: '9963123456',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/haleem/600/400',
    sdgTags: ['SDG2', 'SDG3'],
    location: { type: 'Point', coordinates: [78.4741, 17.3616] }
  },
  {
    foodName: 'Basmati Rice (20 kg)',
    category: 'packaged',
    description: 'Unopened sacks of premium basmati rice — excess procurement from a corporate kitchen.',
    allergens: [],
    quantity: 20,
    quantityUnit: 'kg',
    preparedAt: ago(24),
    shelfLifeHours: 8760, // 1 year
    expiresAt: h(8736),
    pickupWindowStart: now,
    pickupWindowEnd: h(48),
    pickupAddress: { line1: 'Begumpet Corporate Zone', area: 'Begumpet', city: 'Hyderabad', state: 'Telangana', pincode: '500016' },
    contactPhone: '9964234567',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/basmatirice/600/400',
    sdgTags: ['SDG2', 'SDG12'],
    location: { type: 'Point', coordinates: [78.4673, 17.4449] }
  },

  // ── KOLKATA ────────────────────────────────────────────────────────
  {
    foodName: 'Mishti Doi & Sandesh (Confectionery Surplus)',
    category: 'dairy',
    description: 'Sweet shop end-of-day surplus — 60 cups mishti doi and 80 pieces sandesh. Refrigerated.',
    allergens: ['dairy'],
    quantity: 140,
    quantityUnit: 'pieces',
    preparedAt: ago(5),
    shelfLifeHours: 24,
    expiresAt: h(19),
    pickupWindowStart: now,
    pickupWindowEnd: h(4),
    pickupAddress: { line1: 'New Market Area', area: 'New Market', city: 'Kolkata', state: 'West Bengal', pincode: '700087' },
    contactPhone: '9831123456',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/mishtidoi/600/400',
    sdgTags: ['SDG2', 'SDG3'],
    location: { type: 'Point', coordinates: [88.3544, 22.5569] }
  },
  {
    foodName: 'Kathi Rolls (Batch of 90)',
    category: 'non_veg',
    description: 'Lunch surplus from a fast-food chain closing early. Chicken kathi rolls — 90 pieces.',
    allergens: ['gluten', 'egg'],
    quantity: 90,
    quantityUnit: 'pieces',
    preparedAt: ago(2),
    shelfLifeHours: 4,
    expiresAt: h(2),
    pickupWindowStart: now,
    pickupWindowEnd: h(1.5),
    pickupAddress: { line1: 'Park Street Crossing', area: 'Park Street', city: 'Kolkata', state: 'West Bengal', pincode: '700016' },
    contactPhone: '9832234567',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/kathiroll/600/400',
    sdgTags: ['SDG2'],
    location: { type: 'Point', coordinates: [88.3512, 22.5534] }
  },

  // ── PUNE ───────────────────────────────────────────────────────────
  {
    foodName: 'Misal Pav (Event Leftover)',
    category: 'veg',
    description: 'Corporate event leftovers — spicy misal with pav bread. 55 servings ready for pickup.',
    allergens: ['gluten'],
    quantity: 55,
    quantityUnit: 'servings',
    preparedAt: ago(1),
    shelfLifeHours: 5,
    expiresAt: h(4),
    pickupWindowStart: now,
    pickupWindowEnd: h(3),
    pickupAddress: { line1: 'Baner IT Park', area: 'Baner', city: 'Pune', state: 'Maharashtra', pincode: '411045' },
    contactPhone: '9890123456',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/misalpav/600/400',
    sdgTags: ['SDG2', 'SDG12'],
    location: { type: 'Point', coordinates: [73.7898, 18.5597] }
  },
  {
    foodName: 'Seasonal Vegetables (Farm Gate)',
    category: 'raw_produce',
    description: 'Surplus tomatoes, capsicum, spinach, brinjal from Nashik farm market. Organic, pesticide-free.',
    allergens: [],
    quantity: 40,
    quantityUnit: 'kg',
    preparedAt: ago(8),
    shelfLifeHours: 72,
    expiresAt: h(64),
    pickupWindowStart: now,
    pickupWindowEnd: h(20),
    pickupAddress: { line1: 'Shivajinagar Market', area: 'Shivajinagar', city: 'Pune', state: 'Maharashtra', pincode: '411005' },
    contactPhone: '9891234567',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/farmveggies/600/400',
    sdgTags: ['SDG2', 'SDG3', 'SDG12'],
    location: { type: 'Point', coordinates: [73.8474, 18.5308] }
  },

  // ── JAIPUR ─────────────────────────────────────────────────────────
  {
    foodName: 'Dal Bati Churma (Festival Special)',
    category: 'veg',
    description: 'Rajasthani festival feast surplus — dal, bati, churma, and ghee. Served at community function.',
    allergens: ['dairy', 'gluten'],
    quantity: 65,
    quantityUnit: 'servings',
    preparedAt: ago(2),
    shelfLifeHours: 6,
    expiresAt: h(4),
    pickupWindowStart: now,
    pickupWindowEnd: h(3),
    pickupAddress: { line1: 'Johari Bazaar', area: 'Johari Bazaar', city: 'Jaipur', state: 'Rajasthan', pincode: '302003' },
    contactPhone: '9829123456',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/dalbati/600/400',
    sdgTags: ['SDG2', 'SDG17'],
    location: { type: 'Point', coordinates: [75.8235, 26.9185] }
  },
  {
    foodName: 'Packed Milk (NGO Dairy Surplus)',
    category: 'dairy',
    description: '200ml milk packets nearing expiry — untouched, refrigerated. 150 packets available.',
    allergens: ['dairy'],
    quantity: 150,
    quantityUnit: 'pieces',
    preparedAt: ago(12),
    shelfLifeHours: 36,
    expiresAt: h(24),
    pickupWindowStart: now,
    pickupWindowEnd: h(6),
    pickupAddress: { line1: 'Vaishali Nagar Dairy', area: 'Vaishali Nagar', city: 'Jaipur', state: 'Rajasthan', pincode: '302021' },
    contactPhone: '9830234567',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/milkpackets/600/400',
    sdgTags: ['SDG2', 'SDG3'],
    location: { type: 'Point', coordinates: [75.7306, 26.9239] }
  },

  // ── AHMEDABAD ──────────────────────────────────────────────────────
  {
    foodName: 'Gujarati Thali (Caterer Surplus)',
    category: 'veg',
    description: 'Wedding caterer surplus — full Gujarati thali with dal, sabzi, roti, rice, farsan.',
    allergens: ['dairy', 'gluten'],
    quantity: 75,
    quantityUnit: 'servings',
    preparedAt: ago(1),
    shelfLifeHours: 5,
    expiresAt: h(4),
    pickupWindowStart: now,
    pickupWindowEnd: h(2.5),
    pickupAddress: { line1: 'Manek Chowk', area: 'Manek Chowk', city: 'Ahmedabad', state: 'Gujarat', pincode: '380001' },
    contactPhone: '9825123456',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/gujaratithali/600/400',
    sdgTags: ['SDG2', 'SDG12'],
    location: { type: 'Point', coordinates: [72.5865, 23.0225] }
  },
  {
    foodName: 'Dhokla & Thepla (150 packs)',
    category: 'packaged',
    description: 'Snack manufacturer day-end surplus. Steamed dhokla and freshly made thepla. Home-packed.',
    allergens: ['gluten'],
    quantity: 150,
    quantityUnit: 'packets',
    preparedAt: ago(4),
    shelfLifeHours: 24,
    expiresAt: h(20),
    pickupWindowStart: now,
    pickupWindowEnd: h(8),
    pickupAddress: { line1: 'Navrangpura Road', area: 'Navrangpura', city: 'Ahmedabad', state: 'Gujarat', pincode: '380009' },
    contactPhone: '9826234567',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/dhoklathepla/600/400',
    sdgTags: ['SDG2', 'SDG12'],
    location: { type: 'Point', coordinates: [72.5560, 23.0369] }
  }
];

module.exports = MOCK_DONATIONS;
